version: '3.8'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: always

  webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: always

  pdfchat:
    build: ./pdfchat
    ports:
      - "8000:8000"
    volumes:
      - ./pdfchat/data:/app/data
      - ./pdfchat/uploads:/app/uploads
    environment:
      - OLLAMA_BASE=http://ollama:11434
    depends_on:
      - ollama
    restart: always

volumes:
  ollama:
