version: '3.8'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: always
    networks:
      - app-tire

  webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: always
    networks:
      - app-tire

  pdfchat:
    build: ./pdfchat
    ports:
      - "8000:8000"
    volumes:
      - ./pdfchat/data:/app/data
      - ./pdfchat/uploads:/app/uploads
    environment:
      - OLLAMA_BASE=http://ollama:11434
    depends_on:
      - ollama
    restart: always
    networks:
      - app-tire

  python-app:
    image: python:3.11-slim
    container_name: my_python_app
    volumes:
      - .:/app
    working_dir: /app
    command: python main.py
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - app-tire
      
volumes:
  ollama:
