 services:

   portainer:
      image: proxy-repo.saberin.co:8082/portainer/portainer-ce:2.14.1-alpine
      container_name: portainer
      ports:
       - "9000:9000"
      volumes:
        - /etc/locatime:/etc/localtime:ro
        - /var/run/docker.sock:/var/run/docker.sock
        - ./portainer_data:/data
      networks:
        - app-test

networks:
  app-test:
    driver: bridge
